# Pandas

In [1]:
'''
Pandas is a package providing fast , flexible, and expressive data structure designed to make working with relational data

Functions:- Analyzing, cleaning, exploring and manipulating data
'''

'\nPandas is a package providing fast , flexible, and expressive data structure designed to make working with relational data\n\nFunctions:- Analyzing, cleaning, exploring and manipulating data\n'

# DataFrame creation

In [1]:
import pandas as pd

In [6]:
data = {"aakash":[1,1,1,1], "kumar":[2,2,2,2], "singh":[3,3,3,3]}
df = pd.DataFrame(data)
print(df)

   aakash  kumar  singh
0       1      2      3
1       1      2      3
2       1      2      3
3       1      2      3

In [4]:
#File uploading
df1 = pd.read_csv("stock_data.csv")
print(df1)

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [16]:
#Fetching top and last n value
print("Top 2 values\n\n",df1.head(2))
print("\nBottom 2 values\n",df1.tail(2))

Top 2 values

   tickers    eps  revenue price      people
0   GOOGL  27.82       87   845  larry page
1     WMT   4.61      484    65        n.a.

Bottom 2 values
   tickers            eps  revenue price         people
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [5]:
print(df1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   tickers  5 non-null      object
 1   eps      5 non-null      object
 2   revenue  5 non-null      int64
 3   price    5 non-null      object
 4   people   5 non-null      object
dtypes: int64(1), object(4)
memory usage: 328.0+ bytes
None

In [7]:
#percentile,mean,count,std,min,max
#it works in numerical value only
df1.describe()

          revenue
count    5.000000
mean   141.000000
std    195.029485
min     -1.000000
25%     50.000000
50%     85.000000
75%     87.000000
max    484.000000

In [9]:
print(df1.isnull().sum())

tickers    0
eps        0
revenue    0
price      0
people     0
dtype: int64

In [11]:
#Handling DUplicates values
df2 = pd.read_csv("nyc_weather.csv")
print(df2)

          EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
0    1/1/2016           38        23        52                 30.03
1    1/2/2016           36        18        46                 30.02
2    1/3/2016           40        21        47                 29.86
3    1/4/2016           25         9        44                 30.05
4    1/5/2016           20        -3        41                 30.57
5    1/6/2016           33         4        35                 30.50
6    1/7/2016           39        11        33                 30.28
7    1/8/2016           39        29        64                 30.20
8    1/9/2016           44        38        77                 30.16
9   1/10/2016           50        46        71                 29.59
10  1/11/2016           33         8        37                 29.92
11  1/12/2016           35        15        53                 29.85
12  1/13/2016           26         4        42                 29.94
13  1/14/2016           30        12        47                 29.95
14  1/15/2016           43        31        62                 29.82
15  1/16/2016           47        37        70                 29.52
16  1/17/2016           36        23        66                 29.78
17  1/18/2016           25         6        53                 29.83
18  1/19/2016           22         3        42                 30.03
19  1/20/2016           32        15        49                 30.13
20  1/21/2016           31        11        45                 30.15
21  1/22/2016           26         6        41                 30.21
22  1/23/2016           26        21        78                 29.77
23  1/24/2016           28        11        53                 29.92
24  1/25/2016           34        18        54                 30.25
25  1/26/2016           43        29        56                 30.03
26  1/27/2016           41        22        45                 30.03
27  1/28/2016           37        20        51                 29.90
28  1/29/2016           36        21        50                 29.58
29  1/30/2016           34        16        46                 30.01
30  1/31/2016           46        28        52                 29.90

    VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover    Events  \
0                10           8.0               0           5       NaN
1                10           7.0               0           3       NaN
2                10           8.0               0           1       NaN
3                10           9.0               0           3       NaN
4                10           5.0               0           0       NaN
5                10           4.0               0           0       NaN
6                10           2.0               0           3       NaN
7                10           4.0               0           8       NaN
8                 9           8.0               T           8      Rain
9                 4           NaN             1.8           7      Rain
10               10           NaN               0           1       NaN
11               10           6.0               T           4       NaN
12               10          10.0               0           0       NaN
13               10           5.0               T           7       NaN
14                9           5.0               T           2       NaN
15                8           7.0            0.24           7      Rain
16                8           6.0            0.05           6  Fog-Snow
17                9          12.0               T           2      Snow
18               10          11.0               0           1       NaN
19               10           6.0               0           2       NaN
20               10           6.0               0           1       NaN
21                9           NaN            0.01           3      Snow
22                1          16.0            2.31           8  Fog-Snow
23                8           6.0               T           3      Snow
24               10           3.0               0           2       NaN
25               10           7.0               0           2       NaN
26               10           7.0               T           3      Rain
27               10           5.0               0           1       NaN
28               10           8.0               0           4       NaN
29               10           7.0               0           0       NaN
30               10           5.0               0           0       NaN

    WindDirDegrees
0              281
1              275
2              277
3              345
4              333
5              259
6              293
7               79
8               76
9              109
10             289
11             235
12             284
13             266
14             101
15             340
16             345
17             293
18             293
19             302
20             312
21              34
22              42
23             327
24             286
25             244
26             311
27             234
28             298
29             257
30             241

In [15]:
#checking particular column duplicacy
print(df2["EST"].duplicated().sum())

0

In [ ]:
#if we want to delete duplicates value
print(df2.drop_duplicates("EST"))

In [16]:
#missing data
df3 = pd.read_csv("nyc_weather.csv")
print(df3)

          EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
0    1/1/2016           38        23        52                 30.03
1    1/2/2016           36        18        46                 30.02
2    1/3/2016           40        21        47                 29.86
3    1/4/2016           25         9        44                 30.05
4    1/5/2016           20        -3        41                 30.57
5    1/6/2016           33         4        35                 30.50
6    1/7/2016           39        11        33                 30.28
7    1/8/2016           39        29        64                 30.20
8    1/9/2016           44        38        77                 30.16
9   1/10/2016           50        46        71                 29.59
10  1/11/2016           33         8        37                 29.92
11  1/12/2016           35        15        53                 29.85
12  1/13/2016           26         4        42                 29.94
13  1/14/2016           30        12        47                 29.95
14  1/15/2016           43        31        62                 29.82
15  1/16/2016           47        37        70                 29.52
16  1/17/2016           36        23        66                 29.78
17  1/18/2016           25         6        53                 29.83
18  1/19/2016           22         3        42                 30.03
19  1/20/2016           32        15        49                 30.13
20  1/21/2016           31        11        45                 30.15
21  1/22/2016           26         6        41                 30.21
22  1/23/2016           26        21        78                 29.77
23  1/24/2016           28        11        53                 29.92
24  1/25/2016           34        18        54                 30.25
25  1/26/2016           43        29        56                 30.03
26  1/27/2016           41        22        45                 30.03
27  1/28/2016           37        20        51                 29.90
28  1/29/2016           36        21        50                 29.58
29  1/30/2016           34        16        46                 30.01
30  1/31/2016           46        28        52                 29.90

    VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover    Events  \
0                10           8.0               0           5       NaN
1                10           7.0               0           3       NaN
2                10           8.0               0           1       NaN
3                10           9.0               0           3       NaN
4                10           5.0               0           0       NaN
5                10           4.0               0           0       NaN
6                10           2.0               0           3       NaN
7                10           4.0               0           8       NaN
8                 9           8.0               T           8      Rain
9                 4           NaN             1.8           7      Rain
10               10           NaN               0           1       NaN
11               10           6.0               T           4       NaN
12               10          10.0               0           0       NaN
13               10           5.0               T           7       NaN
14                9           5.0               T           2       NaN
15                8           7.0            0.24           7      Rain
16                8           6.0            0.05           6  Fog-Snow
17                9          12.0               T           2      Snow
18               10          11.0               0           1       NaN
19               10           6.0               0           2       NaN
20               10           6.0               0           1       NaN
21                9           NaN            0.01           3      Snow
22                1          16.0            2.31           8  Fog-Snow
23                8           6.0               T           3      Snow
24               10           3.0               0           2       NaN
25               10           7.0               0           2       NaN
26               10           7.0               T           3      Rain
27               10           5.0               0           1       NaN
28               10           8.0               0           4       NaN
29               10           7.0               0           0       NaN
30               10           5.0               0           0       NaN

    WindDirDegrees
0              281
1              275
2              277
3              345
4              333
5              259
6              293
7               79
8               76
9              109
10             289
11             235
12             284
13             266
14             101
15             340
16             345
17             293
18             293
19             302
20             312
21              34
22              42
23             327
24             286
25             244
26             311
27             234
28             298
29             257
30             241

In [17]:
print(df3.isnull().sum())

EST                      0
Temperature              0
DewPoint                 0
Humidity                 0
Sea Level PressureIn     0
VisibilityMiles          0
WindSpeedMPH             3
PrecipitationIn          0
CloudCover               0
Events                  22
WindDirDegrees           0
dtype: int64

In [18]:
#Replace() used to put values on NAN value
import numpy as np

#if we replace with one value then the whole NaN data value will replace which give inccorect answer, so for that we need to specify particular column data

df3["WindSpeedMPH"] = df3["WindSpeedMPH"].replace(np.nan, 6)
print(df3
     )

          EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
0    1/1/2016           38        23        52                 30.03
1    1/2/2016           36        18        46                 30.02
2    1/3/2016           40        21        47                 29.86
3    1/4/2016           25         9        44                 30.05
4    1/5/2016           20        -3        41                 30.57
5    1/6/2016           33         4        35                 30.50
6    1/7/2016           39        11        33                 30.28
7    1/8/2016           39        29        64                 30.20
8    1/9/2016           44        38        77                 30.16
9   1/10/2016           50        46        71                 29.59
10  1/11/2016           33         8        37                 29.92
11  1/12/2016           35        15        53                 29.85
12  1/13/2016           26         4        42                 29.94
13  1/14/2016           30        12        47                 29.95
14  1/15/2016           43        31        62                 29.82
15  1/16/2016           47        37        70                 29.52
16  1/17/2016           36        23        66                 29.78
17  1/18/2016           25         6        53                 29.83
18  1/19/2016           22         3        42                 30.03
19  1/20/2016           32        15        49                 30.13
20  1/21/2016           31        11        45                 30.15
21  1/22/2016           26         6        41                 30.21
22  1/23/2016           26        21        78                 29.77
23  1/24/2016           28        11        53                 29.92
24  1/25/2016           34        18        54                 30.25
25  1/26/2016           43        29        56                 30.03
26  1/27/2016           41        22        45                 30.03
27  1/28/2016           37        20        51                 29.90
28  1/29/2016           36        21        50                 29.58
29  1/30/2016           34        16        46                 30.01
30  1/31/2016           46        28        52                 29.90

    VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover    Events  \
0                10           8.0               0           5       NaN
1                10           7.0               0           3       NaN
2                10           8.0               0           1       NaN
3                10           9.0               0           3       NaN
4                10           5.0               0           0       NaN
5                10           4.0               0           0       NaN
6                10           2.0               0           3       NaN
7                10           4.0               0           8       NaN
8                 9           8.0               T           8      Rain
9                 4           6.0             1.8           7      Rain
10               10           6.0               0           1       NaN
11               10           6.0               T           4       NaN
12               10          10.0               0           0       NaN
13               10           5.0               T           7       NaN
14                9           5.0               T           2       NaN
15                8           7.0            0.24           7      Rain
16                8           6.0            0.05           6  Fog-Snow
17                9          12.0               T           2      Snow
18               10          11.0               0           1       NaN
19               10           6.0               0           2       NaN
20               10           6.0               0           1       NaN
21                9           6.0            0.01           3      Snow
22                1          16.0            2.31           8  Fog-Snow
23                8           6.0               T           3      Snow
24               10           3.0               0           2       NaN
25               10           7.0               0           2       NaN
26               10           7.0               T           3      Rain
27               10           5.0               0           1       NaN
28               10           8.0               0           4       NaN
29               10           7.0               0           0       NaN
30               10           5.0               0           0       NaN

    WindDirDegrees
0              281
1              275
2              277
3              345
4              333
5              259
6              293
7               79
8               76
9              109
10             289
11             235
12             284
13             266
14             101
15             340
16             345
17             293
18             293
19             302
20             312
21              34
22              42
23             327
24             286
25             244
26             311
27             234
28             298
29             257
30             241

In [19]:
df4 = df3
print(df4.isnull().sum())

EST                      0
Temperature              0
DewPoint                 0
Humidity                 0
Sea Level PressureIn     0
VisibilityMiles          0
WindSpeedMPH             0
PrecipitationIn          0
CloudCover               0
Events                  22
WindDirDegrees           0
dtype: int64

In [20]:
#Best way to replace the NaN values is find out mean of column and fill NaN value with mean value
#it wont effect the data too much

In [23]:
#when we want to fill Nan values with backwar and forward value then
df5 = df4
df5["Events"] = df5["Events"].fillna(method = "bfill")  #backward fill
#df5["Events"] = df5["Events"].fillna(method = "bfill")  #forward fill
print(df5)

          EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
0    1/1/2016           38        23        52                 30.03
1    1/2/2016           36        18        46                 30.02
2    1/3/2016           40        21        47                 29.86
3    1/4/2016           25         9        44                 30.05
4    1/5/2016           20        -3        41                 30.57
5    1/6/2016           33         4        35                 30.50
6    1/7/2016           39        11        33                 30.28
7    1/8/2016           39        29        64                 30.20
8    1/9/2016           44        38        77                 30.16
9   1/10/2016           50        46        71                 29.59
10  1/11/2016           33         8        37                 29.92
11  1/12/2016           35        15        53                 29.85
12  1/13/2016           26         4        42                 29.94
13  1/14/2016           30        12        47                 29.95
14  1/15/2016           43        31        62                 29.82
15  1/16/2016           47        37        70                 29.52
16  1/17/2016           36        23        66                 29.78
17  1/18/2016           25         6        53                 29.83
18  1/19/2016           22         3        42                 30.03
19  1/20/2016           32        15        49                 30.13
20  1/21/2016           31        11        45                 30.15
21  1/22/2016           26         6        41                 30.21
22  1/23/2016           26        21        78                 29.77
23  1/24/2016           28        11        53                 29.92
24  1/25/2016           34        18        54                 30.25
25  1/26/2016           43        29        56                 30.03
26  1/27/2016           41        22        45                 30.03
27  1/28/2016           37        20        51                 29.90
28  1/29/2016           36        21        50                 29.58
29  1/30/2016           34        16        46                 30.01
30  1/31/2016           46        28        52                 29.90

    VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover    Events  \
0                10           8.0               0           5      Rain
1                10           7.0               0           3      Rain
2                10           8.0               0           1      Rain
3                10           9.0               0           3      Rain
4                10           5.0               0           0      Rain
5                10           4.0               0           0      Rain
6                10           2.0               0           3      Rain
7                10           4.0               0           8      Rain
8                 9           8.0               T           8      Rain
9                 4           6.0             1.8           7      Rain
10               10           6.0               0           1      Rain
11               10           6.0               T           4      Rain
12               10          10.0               0           0      Rain
13               10           5.0               T           7      Rain
14                9           5.0               T           2      Rain
15                8           7.0            0.24           7      Rain
16                8           6.0            0.05           6  Fog-Snow
17                9          12.0               T           2      Snow
18               10          11.0               0           1      Snow
19               10           6.0               0           2      Snow
20               10           6.0               0           1      Snow
21                9           6.0            0.01           3      Snow
22                1          16.0            2.31           8  Fog-Snow
23                8           6.0               T           3      Snow
24               10           3.0               0           2      Rain
25               10           7.0               0           2      Rain
26               10           7.0               T           3      Rain
27               10           5.0               0           1       NaN
28               10           8.0               0           4       NaN
29               10           7.0               0           0       NaN
30               10           5.0               0           0       NaN

    WindDirDegrees
0              281
1              275
2              277
3              345
4              333
5              259
6              293
7               79
8               76
9              109
10             289
11             235
12             284
13             266
14             101
15             340
16             345
17             293
18             293
19             302
20             312
21              34
22              42
23             327
24             286
25             244
26             311
27             234
28             298
29             257
30             241

# Column Transformation

In [24]:
#If we want to create new column in whic it shows details of "WindSpeedMPH" greate than 6, then loc() will gonna use

df6 = df5
df6.loc[(df6["WindSpeedMPH"] <= 6), "WindSpeed"] = "Normal Wind Speed"
df6.loc[(df6["WindSpeedMPH"] > 6), "WindSpeed"] = "High Wind Speed"
print(df6.head(10))

         EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
0   1/1/2016           38        23        52                 30.03
1   1/2/2016           36        18        46                 30.02
2   1/3/2016           40        21        47                 29.86
3   1/4/2016           25         9        44                 30.05
4   1/5/2016           20        -3        41                 30.57
5   1/6/2016           33         4        35                 30.50
6   1/7/2016           39        11        33                 30.28
7   1/8/2016           39        29        64                 30.20
8   1/9/2016           44        38        77                 30.16
9  1/10/2016           50        46        71                 29.59

   VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover Events  \
0               10           8.0               0           5   Rain
1               10           7.0               0           3   Rain
2               10           8.0               0           1   Rain
3               10           9.0               0           3   Rain
4               10           5.0               0           0   Rain
5               10           4.0               0           0   Rain
6               10           2.0               0           3   Rain
7               10           4.0               0           8   Rain
8                9           8.0               T           8   Rain
9                4           6.0             1.8           7   Rain

   WindDirDegrees          WindSpeed
0             281    High Wind Speed
1             275    High Wind Speed
2             277    High Wind Speed
3             345    High Wind Speed
4             333  Normal Wind Speed
5             259  Normal Wind Speed
6             293  Normal Wind Speed
7              79  Normal Wind Speed
8              76    High Wind Speed
9             109  Normal Wind Speed

In [25]:
df7 = df6
df7["Event + WindSpeed"] = df7["Events"].str.capitalize() +" "+ df7["WindSpeed"].str.capitalize()
print(df7)

          EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
0    1/1/2016           38        23        52                 30.03
1    1/2/2016           36        18        46                 30.02
2    1/3/2016           40        21        47                 29.86
3    1/4/2016           25         9        44                 30.05
4    1/5/2016           20        -3        41                 30.57
5    1/6/2016           33         4        35                 30.50
6    1/7/2016           39        11        33                 30.28
7    1/8/2016           39        29        64                 30.20
8    1/9/2016           44        38        77                 30.16
9   1/10/2016           50        46        71                 29.59
10  1/11/2016           33         8        37                 29.92
11  1/12/2016           35        15        53                 29.85
12  1/13/2016           26         4        42                 29.94
13  1/14/2016           30        12        47                 29.95
14  1/15/2016           43        31        62                 29.82
15  1/16/2016           47        37        70                 29.52
16  1/17/2016           36        23        66                 29.78
17  1/18/2016           25         6        53                 29.83
18  1/19/2016           22         3        42                 30.03
19  1/20/2016           32        15        49                 30.13
20  1/21/2016           31        11        45                 30.15
21  1/22/2016           26         6        41                 30.21
22  1/23/2016           26        21        78                 29.77
23  1/24/2016           28        11        53                 29.92
24  1/25/2016           34        18        54                 30.25
25  1/26/2016           43        29        56                 30.03
26  1/27/2016           41        22        45                 30.03
27  1/28/2016           37        20        51                 29.90
28  1/29/2016           36        21        50                 29.58
29  1/30/2016           34        16        46                 30.01
30  1/31/2016           46        28        52                 29.90

    VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover    Events  \
0                10           8.0               0           5      Rain
1                10           7.0               0           3      Rain
2                10           8.0               0           1      Rain
3                10           9.0               0           3      Rain
4                10           5.0               0           0      Rain
5                10           4.0               0           0      Rain
6                10           2.0               0           3      Rain
7                10           4.0               0           8      Rain
8                 9           8.0               T           8      Rain
9                 4           6.0             1.8           7      Rain
10               10           6.0               0           1      Rain
11               10           6.0               T           4      Rain
12               10          10.0               0           0      Rain
13               10           5.0               T           7      Rain
14                9           5.0               T           2      Rain
15                8           7.0            0.24           7      Rain
16                8           6.0            0.05           6  Fog-Snow
17                9          12.0               T           2      Snow
18               10          11.0               0           1      Snow
19               10           6.0               0           2      Snow
20               10           6.0               0           1      Snow
21                9           6.0            0.01           3      Snow
22                1          16.0            2.31           8  Fog-Snow
23                8           6.0               T           3      Snow
24               10           3.0               0           2      Rain
25               10           7.0               0           2      Rain
26               10           7.0               T           3      Rain
27               10           5.0               0           1       NaN
28               10           8.0               0           4       NaN
29               10           7.0               0           0       NaN
30               10           5.0               0           0       NaN

    WindDirDegrees          WindSpeed           Event + WindSpeed
0              281    High Wind Speed        Rain High wind speed
1              275    High Wind Speed        Rain High wind speed
2              277    High Wind Speed        Rain High wind speed
3              345    High Wind Speed        Rain High wind speed
4              333  Normal Wind Speed      Rain Normal wind speed
5              259  Normal Wind Speed      Rain Normal wind speed
6              293  Normal Wind Speed      Rain Normal wind speed
7               79  Normal Wind Speed      Rain Normal wind speed
8               76    High Wind Speed        Rain High wind speed
9              109  Normal Wind Speed      Rain Normal wind speed
10             289  Normal Wind Speed      Rain Normal wind speed
11             235  Normal Wind Speed      Rain Normal wind speed
12             284    High Wind Speed        Rain High wind speed
13             266  Normal Wind Speed      Rain Normal wind speed
14             101  Normal Wind Speed      Rain Normal wind speed
15             340    High Wind Speed        Rain High wind speed
16             345  Normal Wind Speed  Fog-snow Normal wind speed
17             293    High Wind Speed        Snow High wind speed
18             293    High Wind Speed        Snow High wind speed
19             302  Normal Wind Speed      Snow Normal wind speed
20             312  Normal Wind Speed      Snow Normal wind speed
21              34  Normal Wind Speed      Snow Normal wind speed
22              42    High Wind Speed    Fog-snow High wind speed
23             327  Normal Wind Speed      Snow Normal wind speed
24             286  Normal Wind Speed      Rain Normal wind speed
25             244    High Wind Speed        Rain High wind speed
26             311    High Wind Speed        Rain High wind speed
27             234  Normal Wind Speed                         NaN
28             298    High Wind Speed                         NaN
29             257    High Wind Speed                         NaN
30             241  Normal Wind Speed                         NaN

In [26]:
#if we want to fetch mathematical operations in new column then,

df8 = df7
df8["10% of Humidity"]  = (df8["Humidity"]/100)*10
print(df8)

          EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
0    1/1/2016           38        23        52                 30.03
1    1/2/2016           36        18        46                 30.02
2    1/3/2016           40        21        47                 29.86
3    1/4/2016           25         9        44                 30.05
4    1/5/2016           20        -3        41                 30.57
5    1/6/2016           33         4        35                 30.50
6    1/7/2016           39        11        33                 30.28
7    1/8/2016           39        29        64                 30.20
8    1/9/2016           44        38        77                 30.16
9   1/10/2016           50        46        71                 29.59
10  1/11/2016           33         8        37                 29.92
11  1/12/2016           35        15        53                 29.85
12  1/13/2016           26         4        42                 29.94
13  1/14/2016           30        12        47                 29.95
14  1/15/2016           43        31        62                 29.82
15  1/16/2016           47        37        70                 29.52
16  1/17/2016           36        23        66                 29.78
17  1/18/2016           25         6        53                 29.83
18  1/19/2016           22         3        42                 30.03
19  1/20/2016           32        15        49                 30.13
20  1/21/2016           31        11        45                 30.15
21  1/22/2016           26         6        41                 30.21
22  1/23/2016           26        21        78                 29.77
23  1/24/2016           28        11        53                 29.92
24  1/25/2016           34        18        54                 30.25
25  1/26/2016           43        29        56                 30.03
26  1/27/2016           41        22        45                 30.03
27  1/28/2016           37        20        51                 29.90
28  1/29/2016           36        21        50                 29.58
29  1/30/2016           34        16        46                 30.01
30  1/31/2016           46        28        52                 29.90

    VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover    Events  \
0                10           8.0               0           5      Rain
1                10           7.0               0           3      Rain
2                10           8.0               0           1      Rain
3                10           9.0               0           3      Rain
4                10           5.0               0           0      Rain
5                10           4.0               0           0      Rain
6                10           2.0               0           3      Rain
7                10           4.0               0           8      Rain
8                 9           8.0               T           8      Rain
9                 4           6.0             1.8           7      Rain
10               10           6.0               0           1      Rain
11               10           6.0               T           4      Rain
12               10          10.0               0           0      Rain
13               10           5.0               T           7      Rain
14                9           5.0               T           2      Rain
15                8           7.0            0.24           7      Rain
16                8           6.0            0.05           6  Fog-Snow
17                9          12.0               T           2      Snow
18               10          11.0               0           1      Snow
19               10           6.0               0           2      Snow
20               10           6.0               0           1      Snow
21                9           6.0            0.01           3      Snow
22                1          16.0            2.31           8  Fog-Snow
23                8           6.0               T           3      Snow
24               10           3.0               0           2      Rain
25               10           7.0               0           2      Rain
26               10           7.0               T           3      Rain
27               10           5.0               0           1       NaN
28               10           8.0               0           4       NaN
29               10           7.0               0           0       NaN
30               10           5.0               0           0       NaN

    WindDirDegrees          WindSpeed           Event + WindSpeed  \
0              281    High Wind Speed        Rain High wind speed
1              275    High Wind Speed        Rain High wind speed
2              277    High Wind Speed        Rain High wind speed
3              345    High Wind Speed        Rain High wind speed
4              333  Normal Wind Speed      Rain Normal wind speed
5              259  Normal Wind Speed      Rain Normal wind speed
6              293  Normal Wind Speed      Rain Normal wind speed
7               79  Normal Wind Speed      Rain Normal wind speed
8               76    High Wind Speed        Rain High wind speed
9              109  Normal Wind Speed      Rain Normal wind speed
10             289  Normal Wind Speed      Rain Normal wind speed
11             235  Normal Wind Speed      Rain Normal wind speed
12             284    High Wind Speed        Rain High wind speed
13             266  Normal Wind Speed      Rain Normal wind speed
14             101  Normal Wind Speed      Rain Normal wind speed
15             340    High Wind Speed        Rain High wind speed
16             345  Normal Wind Speed  Fog-snow Normal wind speed
17             293    High Wind Speed        Snow High wind speed
18             293    High Wind Speed        Snow High wind speed
19             302  Normal Wind Speed      Snow Normal wind speed
20             312  Normal Wind Speed      Snow Normal wind speed
21              34  Normal Wind Speed      Snow Normal wind speed
22              42    High Wind Speed    Fog-snow High wind speed
23             327  Normal Wind Speed      Snow Normal wind speed
24             286  Normal Wind Speed      Rain Normal wind speed
25             244    High Wind Speed        Rain High wind speed
26             311    High Wind Speed        Rain High wind speed
27             234  Normal Wind Speed                         NaN
28             298    High Wind Speed                         NaN
29             257    High Wind Speed                         NaN
30             241  Normal Wind Speed                         NaN

    10% of Humidity
0               5.2
1               4.6
2               4.7
3               4.4
4               4.1
5               3.5
6               3.3
7               6.4
8               7.7
9               7.1
10              3.7
11              5.3
12              4.2
13              4.7
14              6.2
15              7.0
16              6.6
17              5.3
18              4.2
19              4.9
20              4.5
21              4.1
22              7.8
23              5.3
24              5.4
25              5.6
26              4.5
27              5.1
28              5.0
29              4.6
30              5.2

# DataFrame COmparison

In [2]:
dict = {"Fruits": ["mango","apple","banana","papaya"],
       "Price": [100,150,50,35],
       "Quantity": [15,10,10,3]}
df9 = pd.DataFrame(dict)
print(df9)

   Fruits  Price  Quantity
0   mango    100        15
1   apple    150        10
2  banana     50        10
3  papaya     35         3

In [3]:
df10 = df9.copy()
print(df10)

   Fruits  Price  Quantity
0   mango    100        15
1   apple    150        10
2  banana     50        10
3  papaya     35         3

In [4]:
#changing values
df10.loc[0,"Price"] = 120
df10.loc[1,"Price"] = 170
df10.loc[2,"Price"] = 150

df10.loc[0,"Quantity"] = 17
df10.loc[1,"Quantity"] = 12
df10.loc[2,"Quantity"] = 15

print(df10)

   Fruits  Price  Quantity
0   mango    120        17
1   apple    170        12
2  banana    150        15
3  papaya     35         3

In [5]:
print(df9.compare(df10))

   Price        Quantity
    self  other     self other
0  100.0  120.0     15.0  17.0
1  150.0  170.0     10.0  12.0
2   50.0  150.0     10.0  15.0